/**
 * The Client Remote assembly mounts the `authorization` and `mcpOAuth`
 * namespaces generated by their controllers. The real `$mount` needs a live
 * Gateway connection; this spec substitutes a recording `remote` service so
 * the roster assertion stays a pure assembly fact.
 */
import { Context } from '@deepseek-ai/cordis'
import { describe, expect, it } from 'vitest'
import type { TypertRemoteContribution } from '@deepseek-ai/dsh-typert-protocol'
import { apply, inject } from '../src/client/index.ts'
import { API_REMOTE_FORWARDED_EVENTS } from '../src/remote-events.ts'

interface RemoteProbe {
  mounted: TypertRemoteContribution[]
  $mount(contribution: TypertRemoteContribution): Promise<() => Promise<void>>
}

async function setup(): Promise<{ remote: RemoteProbe; dispose: () => Promise<void> }> {
  const ctx = new Context()
  const remote: RemoteProbe = {
    mounted: [],
    async $mount(contribution) {
      remote.mounted.push(contribution)
      return async () => {}
    },
  }
  ctx.reflect.provide('remote', remote)
  const fiber = ctx.plugin({ inject: [...inject], apply })
  await fiber
  return {
    remote,
    dispose: async () => { await fiber.dispose(); await ctx.fiber.dispose() },
  }
}

describe('Client Remote assembly mounts the authorization and mcpOAuth namespaces', () => {
  it('mounts the authorization controller contribution', async () => {
    const { remote, dispose } = await setup()
    const contribution = remote.mounted.find(
      c => c.package === '@deepseek-ai/dsh-api-authorization-controller',
    )
    expect(contribution).toBeDefined()
    expect(
      contribution!.descriptors.some(d => d.namespace === 'authorization'),
    ).toBe(true)
    await dispose()
  })

  it('mounts the mcpOAuth controller contribution', async () => {
    const { remote, dispose } = await setup()
    const contribution = remote.mounted.find(
      c => c.package === '@deepseek-ai/dsh-mcp-oauth',
    )
    expect(contribution).toBeDefined()
    expect(
      contribution!.descriptors.some(d => d.namespace === 'mcpOAuth'),
    ).toBe(true)
    await dispose()
  })

  it('forwards the mcp-oauth/status-changed event', () => {
    expect(
      API_REMOTE_FORWARDED_EVENTS.some(e => e.event === 'mcp-oauth/status-changed'),
    ).toBe(true)
  })
})
